---
app_name: pension
app_description: pension application
app_home: "/data/pension"
app_logs_path: "{{ app_home }}/logs"
app_bin_path: "{{ app_home }}/bin"
app_lib_path: "{{ app_home }}/lib"
app_config_path: "{{ app_home }}/config"
app_resources_path: "{{ app_lib_path }}"
app_service_start_and_enable: "{{ 'all' in ansible_run_tags or 'configuration' in ansible_run_tags }}"

app_configurations:
  admin:
    port: 8085
    api.url: "http://api.{{ app_public_domain }}"
    idleTimeout: 120000

  user:
    port: 8086
    api.url: "http://api.{{ app_public_domain }}"
    idleTimeout: 120000
